### ISSUE TITLE
Add or document health checks

### ISSUE THREAD

**Issue by kornysietsma** [jimmikristensen/mountebank-docker#11]
Mountebank can take a bit of time to start - it'd be nice to have a healthcheck option [see the docs](https://docs.docker.com/reference/dockerfile/#healthcheck) so you can wait for it to be fully running before using dependant things.

Alternatively you could just document how to do it in `docker-compose` - below is what I've used - it uses `wget` as alpine doesn't have `curl` (see [this stack overflow discussion](https://stackoverflow.com/questions/47722898/how-can-i-make-a-docker-healthcheck-with-wget-instead-of-curl) ) 

```yml
    healthcheck:
      test: ['CMD', 'wget', '-nv', '-t1', '--spider', 'http://localhost:2525/']
      interval: 4s
      timeout: 30s
      start_period: 3s
```

Then you can run `docker-compose up --wait` to wait for healthy.
